volumes:
  postgres_data:

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:16-alpine
    container_name: bank_cards_database
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=bank_cards
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  app:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_cards_app
    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: ${DB_URL:-jdbc:postgresql://db:5432/bank_cards}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-01234567890123456789012345678901}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET:-01234567890123456789012345678901}