spring:
  application:
    name: bank-cards
  profiles:
    active: dev

  # Общие настройки JPA (вне профилей)
  jpa:
    open-in-view: false

  # Общие настройки Liquibase
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
    enabled: true

application:
  security:
    jwt:
      access-expiration: 900_000 #15 минут в мс
      refresh-expiration: 605_800_000 #7 дней в мс

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method